font:
  normal:
    # family: Iosevka Term Slab
    # family: Rec Mono Duotone
    family: Rec Mono Duotone
    style: Regular

  bold:
    family: Rec Mono Duotone
    style: Bold

  italic:
    family: Rec Mono Duotone
    style: Italic

  bold_italic:
    family: Rec Mono Duotone
    style: Bold Italic

  size: 12
