theme = "slick"
icons = "awesome"

[[block]]
block = "keyboard_layout"
driver = "setxkbmap"
interval = 10
# hide_inactive = true

[[block]]
block = "net"
device = "wlp3s0"
interval = 1

[[block]]
block = "focused_window"

[[block]]
block = "docker"
interval = 5
format = "{running}/{total}/{images}"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mug}G"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1
format = "{barchart}"

[[block]]
block = "cpu"
interval = 2
format = "{frequency}"

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

# [[block]]
# block = "sound"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"

[[block]]
block = "battery"
interval = 10
format = "{percentage}% {time}"
